#pragma once

/*
*
*	Autogenerated file, contains function definition for
*	every CPU instruction with opcode from 00 to FF.
*
*/

#define DECLARE_INSTRUCTIONS \
			void instr_00(); void instr_01(); void instr_02(); void instr_03();          \
			void instr_04(); void instr_05(); void instr_06(); void instr_07();          \
			void instr_08(); void instr_09(); void instr_0A(); void instr_0B();          \
			void instr_0C(); void instr_0D(); void instr_0E(); void instr_0F();          \
			void instr_10(); void instr_11(); void instr_12(); void instr_13();          \
			void instr_14(); void instr_15(); void instr_16(); void instr_17();          \
			void instr_18(); void instr_19(); void instr_1A(); void instr_1B();          \
			void instr_1C(); void instr_1D(); void instr_1E(); void instr_1F();          \
			void instr_20(); void instr_21(); void instr_22(); void instr_23();          \
			void instr_24(); void instr_25(); void instr_26(); void instr_27();          \
			void instr_28(); void instr_29(); void instr_2A(); void instr_2B();          \
			void instr_2C(); void instr_2D(); void instr_2E(); void instr_2F();          \
			void instr_30(); void instr_31(); void instr_32(); void instr_33();          \
			void instr_34(); void instr_35(); void instr_36(); void instr_37();          \
			void instr_38(); void instr_39(); void instr_3A(); void instr_3B();          \
			void instr_3C(); void instr_3D(); void instr_3E(); void instr_3F();          \
			void instr_40(); void instr_41(); void instr_42(); void instr_43();          \
			void instr_44(); void instr_45(); void instr_46(); void instr_47();          \
			void instr_48(); void instr_49(); void instr_4A(); void instr_4B();          \
			void instr_4C(); void instr_4D(); void instr_4E(); void instr_4F();          \
			void instr_50(); void instr_51(); void instr_52(); void instr_53();          \
			void instr_54(); void instr_55(); void instr_56(); void instr_57();          \
			void instr_58(); void instr_59(); void instr_5A(); void instr_5B();          \
			void instr_5C(); void instr_5D(); void instr_5E(); void instr_5F();          \
			void instr_60(); void instr_61(); void instr_62(); void instr_63();          \
			void instr_64(); void instr_65(); void instr_66(); void instr_67();          \
			void instr_68(); void instr_69(); void instr_6A(); void instr_6B();          \
			void instr_6C(); void instr_6D(); void instr_6E(); void instr_6F();          \
			void instr_70(); void instr_71(); void instr_72(); void instr_73();          \
			void instr_74(); void instr_75(); void instr_76(); void instr_77();          \
			void instr_78(); void instr_79(); void instr_7A(); void instr_7B();          \
			void instr_7C(); void instr_7D(); void instr_7E(); void instr_7F();          \
			void instr_80(); void instr_81(); void instr_82(); void instr_83();          \
			void instr_84(); void instr_85(); void instr_86(); void instr_87();          \
			void instr_88(); void instr_89(); void instr_8A(); void instr_8B();          \
			void instr_8C(); void instr_8D(); void instr_8E(); void instr_8F();          \
			void instr_90(); void instr_91(); void instr_92(); void instr_93();          \
			void instr_94(); void instr_95(); void instr_96(); void instr_97();          \
			void instr_98(); void instr_99(); void instr_9A(); void instr_9B();          \
			void instr_9C(); void instr_9D(); void instr_9E(); void instr_9F();          \
			void instr_A0(); void instr_A1(); void instr_A2(); void instr_A3();          \
			void instr_A4(); void instr_A5(); void instr_A6(); void instr_A7();          \
			void instr_A8(); void instr_A9(); void instr_AA(); void instr_AB();          \
			void instr_AC(); void instr_AD(); void instr_AE(); void instr_AF();          \
			void instr_B0(); void instr_B1(); void instr_B2(); void instr_B3();          \
			void instr_B4(); void instr_B5(); void instr_B6(); void instr_B7();          \
			void instr_B8(); void instr_B9(); void instr_BA(); void instr_BB();          \
			void instr_BC(); void instr_BD(); void instr_BE(); void instr_BF();          \
			void instr_C0(); void instr_C1(); void instr_C2(); void instr_C3();          \
			void instr_C4(); void instr_C5(); void instr_C6(); void instr_C7();          \
			void instr_C8(); void instr_C9(); void instr_CA(); void instr_CB();          \
			void instr_CC(); void instr_CD(); void instr_CE(); void instr_CF();          \
			void instr_D0(); void instr_D1(); void instr_D2(); void instr_D3();          \
			void instr_D4(); void instr_D5(); void instr_D6(); void instr_D7();          \
			void instr_D8(); void instr_D9(); void instr_DA(); void instr_DB();          \
			void instr_DC(); void instr_DD(); void instr_DE(); void instr_DF();          \
			void instr_E0(); void instr_E1(); void instr_E2(); void instr_E3();          \
			void instr_E4(); void instr_E5(); void instr_E6(); void instr_E7();          \
			void instr_E8(); void instr_E9(); void instr_EA(); void instr_EB();          \
			void instr_EC(); void instr_ED(); void instr_EE(); void instr_EF();          \
			void instr_F0(); void instr_F1(); void instr_F2(); void instr_F3();          \
			void instr_F4(); void instr_F5(); void instr_F6(); void instr_F7();          \
			void instr_F8(); void instr_F9(); void instr_FA(); void instr_FB();          \
			void instr_FC(); void instr_FD(); void instr_FE(); void instr_FF();          

#define DECLARE_INSTRUCTIONS_TABLE                                                    \
		type_instr instr_table[256] =                                                 \
        {                                                                             \
			& CPU::instr_00, & CPU::instr_01, & CPU::instr_02, & CPU::instr_03,       \
			& CPU::instr_04, & CPU::instr_05, & CPU::instr_06, & CPU::instr_07,       \
			& CPU::instr_08, & CPU::instr_09, & CPU::instr_0A, & CPU::instr_0B,       \
			& CPU::instr_0C, & CPU::instr_0D, & CPU::instr_0E, & CPU::instr_0F,       \
			& CPU::instr_10, & CPU::instr_11, & CPU::instr_12, & CPU::instr_13,       \
			& CPU::instr_14, & CPU::instr_15, & CPU::instr_16, & CPU::instr_17,       \
			& CPU::instr_18, & CPU::instr_19, & CPU::instr_1A, & CPU::instr_1B,       \
			& CPU::instr_1C, & CPU::instr_1D, & CPU::instr_1E, & CPU::instr_1F,       \
			& CPU::instr_20, & CPU::instr_21, & CPU::instr_22, & CPU::instr_23,       \
			& CPU::instr_24, & CPU::instr_25, & CPU::instr_26, & CPU::instr_27,       \
			& CPU::instr_28, & CPU::instr_29, & CPU::instr_2A, & CPU::instr_2B,       \
			& CPU::instr_2C, & CPU::instr_2D, & CPU::instr_2E, & CPU::instr_2F,       \
			& CPU::instr_30, & CPU::instr_31, & CPU::instr_32, & CPU::instr_33,       \
			& CPU::instr_34, & CPU::instr_35, & CPU::instr_36, & CPU::instr_37,       \
			& CPU::instr_38, & CPU::instr_39, & CPU::instr_3A, & CPU::instr_3B,       \
			& CPU::instr_3C, & CPU::instr_3D, & CPU::instr_3E, & CPU::instr_3F,       \
			& CPU::instr_40, & CPU::instr_41, & CPU::instr_42, & CPU::instr_43,       \
			& CPU::instr_44, & CPU::instr_45, & CPU::instr_46, & CPU::instr_47,       \
			& CPU::instr_48, & CPU::instr_49, & CPU::instr_4A, & CPU::instr_4B,       \
			& CPU::instr_4C, & CPU::instr_4D, & CPU::instr_4E, & CPU::instr_4F,       \
			& CPU::instr_50, & CPU::instr_51, & CPU::instr_52, & CPU::instr_53,       \
			& CPU::instr_54, & CPU::instr_55, & CPU::instr_56, & CPU::instr_57,       \
			& CPU::instr_58, & CPU::instr_59, & CPU::instr_5A, & CPU::instr_5B,       \
			& CPU::instr_5C, & CPU::instr_5D, & CPU::instr_5E, & CPU::instr_5F,       \
			& CPU::instr_60, & CPU::instr_61, & CPU::instr_62, & CPU::instr_63,       \
			& CPU::instr_64, & CPU::instr_65, & CPU::instr_66, & CPU::instr_67,       \
			& CPU::instr_68, & CPU::instr_69, & CPU::instr_6A, & CPU::instr_6B,       \
			& CPU::instr_6C, & CPU::instr_6D, & CPU::instr_6E, & CPU::instr_6F,       \
			& CPU::instr_70, & CPU::instr_71, & CPU::instr_72, & CPU::instr_73,       \
			& CPU::instr_74, & CPU::instr_75, & CPU::instr_76, & CPU::instr_77,       \
			& CPU::instr_78, & CPU::instr_79, & CPU::instr_7A, & CPU::instr_7B,       \
			& CPU::instr_7C, & CPU::instr_7D, & CPU::instr_7E, & CPU::instr_7F,       \
			& CPU::instr_80, & CPU::instr_81, & CPU::instr_82, & CPU::instr_83,       \
			& CPU::instr_84, & CPU::instr_85, & CPU::instr_86, & CPU::instr_87,       \
			& CPU::instr_88, & CPU::instr_89, & CPU::instr_8A, & CPU::instr_8B,       \
			& CPU::instr_8C, & CPU::instr_8D, & CPU::instr_8E, & CPU::instr_8F,       \
			& CPU::instr_90, & CPU::instr_91, & CPU::instr_92, & CPU::instr_93,       \
			& CPU::instr_94, & CPU::instr_95, & CPU::instr_96, & CPU::instr_97,       \
			& CPU::instr_98, & CPU::instr_99, & CPU::instr_9A, & CPU::instr_9B,       \
			& CPU::instr_9C, & CPU::instr_9D, & CPU::instr_9E, & CPU::instr_9F,       \
			& CPU::instr_A0, & CPU::instr_A1, & CPU::instr_A2, & CPU::instr_A3,       \
			& CPU::instr_A4, & CPU::instr_A5, & CPU::instr_A6, & CPU::instr_A7,       \
			& CPU::instr_A8, & CPU::instr_A9, & CPU::instr_AA, & CPU::instr_AB,       \
			& CPU::instr_AC, & CPU::instr_AD, & CPU::instr_AE, & CPU::instr_AF,       \
			& CPU::instr_B0, & CPU::instr_B1, & CPU::instr_B2, & CPU::instr_B3,       \
			& CPU::instr_B4, & CPU::instr_B5, & CPU::instr_B6, & CPU::instr_B7,       \
			& CPU::instr_B8, & CPU::instr_B9, & CPU::instr_BA, & CPU::instr_BB,       \
			& CPU::instr_BC, & CPU::instr_BD, & CPU::instr_BE, & CPU::instr_BF,       \
			& CPU::instr_C0, & CPU::instr_C1, & CPU::instr_C2, & CPU::instr_C3,       \
			& CPU::instr_C4, & CPU::instr_C5, & CPU::instr_C6, & CPU::instr_C7,       \
			& CPU::instr_C8, & CPU::instr_C9, & CPU::instr_CA, & CPU::instr_CB,       \
			& CPU::instr_CC, & CPU::instr_CD, & CPU::instr_CE, & CPU::instr_CF,       \
			& CPU::instr_D0, & CPU::instr_D1, & CPU::instr_D2, & CPU::instr_D3,       \
			& CPU::instr_D4, & CPU::instr_D5, & CPU::instr_D6, & CPU::instr_D7,       \
			& CPU::instr_D8, & CPU::instr_D9, & CPU::instr_DA, & CPU::instr_DB,       \
			& CPU::instr_DC, & CPU::instr_DD, & CPU::instr_DE, & CPU::instr_DF,       \
			& CPU::instr_E0, & CPU::instr_E1, & CPU::instr_E2, & CPU::instr_E3,       \
			& CPU::instr_E4, & CPU::instr_E5, & CPU::instr_E6, & CPU::instr_E7,       \
			& CPU::instr_E8, & CPU::instr_E9, & CPU::instr_EA, & CPU::instr_EB,       \
			& CPU::instr_EC, & CPU::instr_ED, & CPU::instr_EE, & CPU::instr_EF,       \
			& CPU::instr_F0, & CPU::instr_F1, & CPU::instr_F2, & CPU::instr_F3,       \
			& CPU::instr_F4, & CPU::instr_F5, & CPU::instr_F6, & CPU::instr_F7,       \
			& CPU::instr_F8, & CPU::instr_F9, & CPU::instr_FA, & CPU::instr_FB,       \
			& CPU::instr_FC, & CPU::instr_FD, & CPU::instr_FE, & CPU::instr_FF        \
		};